animal = " Dragon chino "
print(animal.upper())
print(animal.lower())
print(animal.capitalize())
print(animal.title())
print(animal.strip())
print(animal.strip().title())
print("gó" in animal)
print("go" not in animal)
print(animal.replace("go", "gó"))
